name: Deploy to EC2

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      - name: git pull & deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          cd ~/fundmate-be
          git pull origin main

          # ─── .env 파일 생성 ───────────────────────────────────────────
          cat > .env << 'EOL'
          API_GATEWAY_PORT=3000
          AI_SERVICE_PORT=3001
          AUTH_SERVICE_PORT=3002
          FUNDING_SERVICE_PORT=3003
          INTERACTION_SERVICE_PORT=3004
          PAYMENT_SERVICE_PORT=3005
          PUBLIC_SERVICE_PORT=3006
          USER_SERVICE_PORT=3007
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_PORT=3306
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          HOST=0.0.0.0
          SMTP_SERVICE = Gmail
          SMTP_USER = fundmate0721@gmail.com
          SMTP_PASSWORD = ${{ secrets.SMTP_PASSWORD }}
          PRIVATE_KEY = ${{ secrets.PRIVATE_KEY}}
          REFRESH_TOKEN_SECRET = ${{ secrets.REFRESH_TOKEN_SECRET}}!
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}
          GOOGLE_REDIRECT_URI=http://localhost:5000/oauth/google/callback
          KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
          KAKAO_REDIRECT_URI=http://localhost:5000/oauth/kakao/callback
          NAVER_CLIENT_ID=${{secrets.NAVER_CLIENT_ID}}
          NAVER_CLIENT_SECRET=${{secrets.NAVER_CLIENT_SECRET}}
          NAVER_REDIRECT_URI=http://localhost:5000/oauth/naver/callback 
          PUBLIC_CONSUMER_KEY=${{secrets.PUBLIC_CONSUMER_KEY}}
          PUBLIC_CONSUMER_SECRET=${{secrets.PUBLIC_CONSUMER_SECRET}}
          AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}}
          AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}}}
          AWS_REGION=${{secrets.AWS_REGION}}
          AWS_BUCKET=${{secrets.AWS_BUCKET}}
          EOL

          sudo docker system prune -a --volumes --force
          sudo apt-get clean
          sudo rm -rf /home/ubuntu/.vscode-serve
          chmod +x switch-blue-green.sh
          ./switch-blue-green.sh

          EOF
